openapi: 3.0.0
info:
  title: Referral System API
  version: 1.0.0
  description: API for Referral System
servers:
  - url: http://localhost:3000/api/referral-system
    description: Local server

components: 
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string 
        email:
          type: string
  
paths:
  /agent/me:
    get:
      summary: Get agent details
      responses:
        '200':
          description: Agent details retreived successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  name:
                    type: string
                  email:
                    type: string
                  phoneNumber:
                    type: string
                  address:
                    type: string
                  userProfileCompleteStatus:
                    type: boolean
                  totalEarningAmount:
                    type: number
                  pendingWithdrawalAmount:
                    type: number
                  balance:
                    type: number
                  pendingBalance:
                    type: number
                  bankAccounts:
                    type: array
                    items: 
                      type: object
                      properties:
                        bankName:
                          type: string
                        accountHolderName:
                          type: string
                        accountNumber:
                          type: string
                        ifscCode:
                          type: string
                        accountType:
                          type: string
                        isPrimary: 
                          type: boolean
                        isVerified:
                          type: boolean 
                

                  

