name: Deploy Docker Image to EC2 (Amazon Linux)

on:
  push:
    branches: [main]

env:
  DOCKER_IMAGE: adeshsingh15/referral # Your Docker Hub image

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag Docker image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker tag $DOCKER_IMAGE $DOCKER_IMAGE:latest

      - name: Push to Docker Hub
        run: docker push $DOCKER_IMAGE

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          # 1. Create and secure SSH key
          echo "$PRIVATE_KEY" > deploy-key.pem
          chmod 600 deploy-key.pem

          # 2. Connect to EC2 and deploy with all variables explicitly passed
          ssh -o StrictHostKeyChecking=no -i deploy-key.pem ${USER}@${HOST} "
            # 3. Install Docker if not available
            if ! command -v docker &> /dev/null; then
              echo 'Installing Docker...'
              sudo yum update -y || { echo 'Update failed'; exit 1; }
              sudo yum install docker -y || { echo 'Docker install failed'; exit 1; }
              sudo service docker start || { echo 'Docker start failed'; exit 1; }
              sudo usermod -a -G docker ec2-user
              sudo chkconfig docker on
            else
              echo 'Docker is already installed.'
            fi

            # Enable super user
            sudo su

            # 4. Stop and remove previous container (if any)
            # docker stop referral || true
            # docker rm referral || true

            # 5. Pull the latest Docker image (with debug output)
            echo 'Attempting to pull image: $DOCKER_IMAGE'
            for i in {1..3}; do
              if docker pull '$DOCKER_IMAGE'; then
                echo 'Successfully pulled image'
                break
              else
                echo 'Pull attempt $i failed'
                sleep 5
                [ \$i -eq 3 ] && { echo 'Failed to pull image after 3 attempts'; exit 1; }
              fi
            done

            # 6. Run the new container
            docker run -d \
              --name referral \
              --restart unless-stopped \
              --env-file prod.env \
              '$DOCKER_IMAGE' || { echo 'Container failed to start'; exit 1; }

            # 7. Confirm container is running
            sleep 10
            docker ps | grep referral || { echo 'Container not running'; exit 1; }
          "
